
CREATE TABLE User (
    user_id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    password varchar(255),
    firstname varchar(255),
    lastname varchar(255),
    email varchar(255),
    address1 varchar(255),
    address2 varchar(255),
    city varchar(12),
    state varchar(255),
    zip varchar(12),
    country varchar(12),
    credit_card_type varchar(255),
    credit_card_number int,
    credit_card_cvv int,
    credit_card_expiry varchar(25),
    last_login varchar(255)
);

CREATE TABLE Game (
    game_id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    game_name varchar(255),
    game_description varchar(2555),
    console varchar(255),
    num_players int,
    coop boolean,
    genre varchar(12),
    release_date varchar(20),
    developer varchar(255),
    publisher varchar(255),
    front_box_art varchar(255),
    back_box_art varchar(255),
    logo varchar(255),
    developer_logo varchar(255),
    price int,
    discount int
);


CREATE TABLE Comments (
    comment_id int,
    user_id int,
    game_id int,
    comment_date varchar(255),
    comment_details varchar(255),
    ratings int
);

INSERT INTO User (
  password,
  firstname,
  lastname,
  email,
  address1,
  address2,
  city,
  state,
  zip,
  country,
  credit_card_type,
  credit_card_number,
  credit_card_cvv,
  credit_card_expiry
)
VALUES (
  '123',
  'Eska',
  'Moon',
  'test@gmail.com',
  '6666 Code Street',
  '123 Bug Street',
  'Montreal',
  'Quebec',
  'H1S1K1',
  'Canada',
  'Mastercard',
  '1234567890',
  '123',
  '1712'
);

-- A total of 56 data entries
INSERT INTO Game(
    game_name,
    game_description,
    console,
    num_players,
    coop,
    genre,
    release_date,
    developer,
    publisher,
    front_box_art,
    back_box_art,
    logo,
    developer_logo,
    price,
    discount
) VALUES
(
	'Marvel vs. Capcom 2',
	'Marvel vs. Capcom 2: New Age of Heroes is a fighting game, developed and published by Capcom. It is the fourth game in the Marvel vs. Capcom series of fighting games. With the fourth installment of this series, Capcom simplified the player controls to make the gameplay more accessible to the wider audience of casual players. The button configuration was trimmed down to 4 main buttons and 2 assist buttons. The game also features a different air-combo system and 3 on 3 tag, compared to the 2 on 2 tag from previous games in the series.',
	'Microsoft Xbox 360',
	'2',
	'false',
	'fighting',
	'06/30/2000',
	'Capcom',
	'Capcom',
	'http://thegamesdb.net/banners/boxart/original/front/2244-1.jpg',
	'http://thegamesdb.net/banners/boxart/original/back/2244-1.jpg',
	'http://thegamesdb.net/banners/clearlogo/2244.png',
	'http://thegamesdb.net/banners/_gameviewcache/publishers/8-folder.png',
	'14.99',
	'10'
), (
	'The Legend of Zelda: Breath of the Wild',
	"The Legend of Zelda: Breath of the Wild is an action-adventure video game developed and published by Nintendo for the Nintendo Switch and Wii U video game consoles. The game is a part of The Legend of Zelda series, and follows amnesiac protagonist Link, who awakens from a hundred-year slumber to a mysterious voice that guides him to defeat Calamity Ganon before he can destroy the kingdom of Hyrule.

	The title's gameplay and mechanics constitute a departure from the series' usual conventions, featuring an open-world environment, a detailed physics engine, high-definition visuals, and voice acting. Announced in 2013, the game was initially planned for release as a Wii U exclusive in 2015, but was delayed twice prior to its release on March 3, 2017. Breath of the Wild was a launch title for the Switch, as well as the final Nintendo-produced game for the Wii U.

	Breath of the Wild received universal acclaim from critics, who deemed it to be one of the greatest video games of all time. Critics praised the game's open-ended, physics-driven gameplay that encourages player experimentation and exploration, with many calling it a landmark title in open-world game design, although minor criticism was directed at the game's technical performance at launch.",
	'Nintendo Switch',
	'1',
	'false',
	'action, adventure',
	'03/03/2017',
	'Nintendo',
	'Nintendo',
	'http://thegamesdb.net/banners/boxart/original/front/42293-1.jpg',
	'',
	'http://thegamesdb.net/banners/clearlogo/42293.png',
	'http://thegamesdb.net/banners/_gameviewcache/publishers/0-nintendo.png',
	'19.99',
	'12'
), (
	'P.T.',
	"P.T. (Playable Teaser) is a first-person psychological survival horror video game directed by Hideo Kojima, developed by Kojima Productions, and published by Konami. Released for the PlayStation 4 on 12 August 2014 as a free download on the PlayStation Network, P.T. served as an interactive teaser for the game Silent Hills, a cancelled installment in the Silent Hill series. In P.T., the player explores a looping corridor of a haunted house while experiencing supernatural events.

	P.T. was met with a positive critical reception. It was praised for its horror and the execution of the looping corridor, but was criticized for its complicated puzzles. After the cancellation of Silent Hills, Konami removed P.T. from the PlayStation Store and eliminated the ability to re-download the game. These changes were the subject of controversy.",
	'Sony Playstation 4',
	'1',
	'false',
	'horror, puzzle',
	'08/12/2014',
	'Kojima Productions',
	'Konami',
	'http://thegamesdb.net/banners/boxart/original/front/26370-1.png',
	'',
	'http://thegamesdb.net/banners/clearlogo/26370.png',
	'http://thegamesdb.net/banners/_gameviewcache/publishers/35-folder.png',
	'10.99',
	'3'
), (
	'Metal Gear Solid HD Collection',
	"From the critically acclaimed director, Hideo Kojima, Metal Gear Solid HD Collection offers a handful of the most popular Metal Gear Solid titles from the past in true HD for the first time ever. Featuring three complete games, Metal Gear Solid 2: Sons of Liberty, Metal Gear Solid: Snake Eater and Metal Gear Solid: Peace Walker, the HD Collection offers old and new fans a chance to experience the epic game play, design and storytelling of the MGS franchise. The 'Metal Gear Solid (MGS)' series is the seminal work of Hideo Kojima, Japan's master game creator, and the progenitor of the stealth action game genre. The series has become a global phenomenon, with over 27 million copies sold worldwide. The player controls a secret agent from an elite special forces unit who is sent on solo sneaking missions through enemy installations, vast jungles, and sometimes even the thick of battle. Alone and surrounded by the enemy, even a special forces agent will find it tough to come out alive. But that is the secret behind the series' popularity-the cerebral challenge of figuring out how to avoid combat, and the thrill of sneaking through enemy territory undetected. The MGS series is also known for its storyline, which blends seamlessly with the gameplay. The scenarios are based on extensive research and incorporate the drama of actual developments in society. These elements have made MGS what it is today: a mature work of entertainment that transcends national borders and the confines of video games, and one of the leading products of the Japanese content business.",
	'Sony Playstation 3',
	'1',
	'false',
	'stealth',
	'11/08/2011',
	'Kojima Productions',
	'Konami',
	'http://thegamesdb.net/banners/boxart/original/front/12306-1.jpg',
	'http://thegamesdb.net/banners/boxart/original/back/12306-1.jpg',
	'',
	'http://thegamesdb.net/banners/_gameviewcache/publishers/35-folder.png',
	'12.99',
	'10'
), (
	'Oddworld: New n Tasty',
	"Abe's back, and the original hero's about to face his oddest challenge yet!Chosen by the fickle finger of fate, Abe, first class Floor-Waxer for RuptureFarms, was catapulted into a life of adventure when he overheard plans from his boss, Molluck the Glukkon, to turn Abe and his fellow Mudokons into Tasty Treats as part of a last-ditch effort to rescue Molluck’s failing meatpacking empire.

	Can Abe change the fate of thousands and rescue the Mudokons? Can he escape the dark recesses of RuptureFarms and the desolate, uninviting, and downright terrifying surrounding environment?Lead our unlikely hero on his mission because if he doesn’t make it… Abe’s back on the menu!",
	'Sony Playstation 3',
	'1',
	'false',
	'platform, puzzle',
	'04/21/2015',
	'Just Add Water',
	'Oddworld Inhabitants, Inc',
	'http://thegamesdb.net/banners/boxart/original/front/21749-1.jpg',
	'',
	'http://thegamesdb.net/banners/clearlogo/21749.png',
	'http://thegamesdb.net/banners/_gameviewcache/publishers/0-DistinctiveDevelopments.png',
	'8.99',
	'3'
), (
	'Super Smash Bros: Project M',
	"Project M is a community-made mod of Brawl inspired by Super Smash Bros. Melee's gameplay designed to add rich, technical gameplay to a balanced cast of characters while additionally enhancing the speed of play. Project M employs new codes which seamlessly add in new, universal features to the entire cast to add technical variety to all characters.",
	'Nintendo Wii',
	'4',
	'false',
	'fighting',
	'11/01/2014',
	'Project M Development Team',
	'Project M Development Team',
	'http://thegamesdb.net/banners/boxart/original/front/28382-1.png',
	'',
	'',
	'http://thegamesdb.net/banners/_gameviewcache/publishers/1-Acclaim.png',
	'19.99',
	'12'
), (
	'2020 Super Baseball',
	"Super Baseball 2020 is a futuristic baseball video game. It was first released in Japan for the Neo Geo in 1991, and then it was later released in North America for the Mega Drive/Genesis (ported by NuFX and released by Electronic Arts) and Super Nintendo Entertainment System (released by Tradewest) in 1993.

	The game follows the basic rules of baseball, but there are several upgrades since the game takes place in the year 2020. The most obvious difference from real baseball is that some of the characters in this game are robots. All the human characters are equipped with powerful armor, computer sensors, and jet-packs for improved offense and defensive skills.",
	'Arcade',
	'1',
	'false',
	'sports',
	'01/01/1991',
	'Snk',
	'Snk',
	'http://thegamesdb.net/banners/boxart/original/front/29088-1.jpg',
	'http://thegamesdb.net/banners/boxart/original/back/29088-1.jpg',
	'',
	'http://thegamesdb.net/banners/_gameviewcache/publishers/59-folder.png',
	'8.99',
	'1'
), (
	'Tac Tiles',
	"A colorful and challenging puzzle game for smartphones and tablets.
	The target is to change a board of multiple colored tiles to a single color with a limited number of moves. A progression of increasingly hard levels await players, and the only tool available is a set of colors for modifying the board. Players must use them intelligently, and create chain reactions to connect as many tiles as possible before running out of moves.",
	'Android',
	'1',
	'false',
	'puzzle',
	'12/11/2015',
	'',
	'',
	'http://thegamesdb.net/banners/boxart/original/front/34417-1.jpg',
	'',
	'',
	'',
	'4.99',
	'10'
), (
	'StarCraft II: Legacy of the Void',
	"You are Hierarch Artanis, leader of the mighty protoss race. Years ago, your homeworld of Aiur fell to the merciless zerg Swarm. Now, at long last, you have raised a powerful fleet of warships known as the Golden Armada, and are poised to reclaim your world. But an ancient evil—Amon—threatens this destiny and the fate of the entire galaxy. Only you can reunite the protoss factions and defeat the coming darkness before it consumes all life in the sector.",
	'PC',
	'4',
	'false',
	'strategy',
	'11/10/2015',
	'Blizzard',
	'Blizzard',
	'http://thegamesdb.net/banners/boxart/original/front/26511-1.jpg',
	'',
	'',
	'http://thegamesdb.net/banners/_gameviewcache/publishers/1-Blizzard_Entertainment_Logo.svg.png',
	'24.99',
	'10'
), (
	'Rolie Polie Olie 2',
	"The show focuses on the Polie Family, who live in a teapot-shaped house in a geometric world (Planet Polie) populated by robot-based characters. The stories revolve around a young robot named Olie learning life lessons and going on wacky adventures (either real or imaginative) while growing up. These often include his little sister Zowie, his inventor father, his hard-working mom, his fun-loving grandfather Pappy, and his dog Spot. Although most of the main cast is composed of circular bots, other characters are featured in other shapes, such as Olie's friend Billy Bevel and his family, who are square-shaped bots from Planet Cubey.",
	'Microsoft Xbox One',
	'4',
	'true',
	'action, adventure, puzzle, role-playing',
	'06/01/2016',
	'Bandai Namco Games',
	'Bandai Namco Studios',
	'http://www.cdaccess.com/jpg/shared/front/large/roliepol.jpg',
	'',
	'',
	'http://thegamesdb.net/banners/_gameviewcache/publishers/5-folder.png',
	'4.99',
	'0'
), (
	'Space Manbow',
	"In the year 189 of the stellar calendar, humanity happened upon the ruins of an ancient (and, if the st. 7 decor is anything to go by, rather decadent and malicious) civilization, and sent an archaeological crew to explore them. However, the crew managed to activate the ruins' defense system.

	The system operated by identifying the Sol system as the intruders' origin, then launched the Sun-Fish ('Manbou' being Japanese for 'Sunfish'), an ultimate weapon bio-mechanical starship capable of destroying an entire solar system and protected by an impregnable force-field bubble. The surviving members of the crew, however, find a chance to stop the Sun-Fish. By using an unearthed Manbou-J (i.e. Junior Sun-Fish) fighter and activating a teleportation system in the deepest part of the ruins, one pilot, Cleaver Mule, can actually get inside the force bubble and destroy the Sun-Fish from there.",
	'MSX',
	'1',
	'false',
	'shoot',
	'12/21/1989',
	'Konami',
	'Konami',
	'http://thegamesdb.net/banners/boxart/original/front/27101-1.jpg',
	'http://thegamesdb.net/banners/boxart/original/back/27101-1.jpg',
	'',
	'http://thegamesdb.net/banners/_gameviewcache/publishers/35-folder.pngg',
	'12.99',
	'5'
), (
	'Tecmo Super Bowl',
	"The teams, the players, and the halftime shows are ready for the ultimate football season, and you're in control. From the first pre-season game to the playoffs, it's your call, your skill, and your team. Can you get to and win the Super Bowl? Tecmo Super Bowl is the only football game to feature onside kicks, blocked passes and kicks, fumbles, pitchout to the running back, player injuries, time-outs, and much, much more! For 1 or 2 players. All 28 NFL teams! Four running plays, four passing plays. Team stats and data. Create your own Pro Bowl. Coach Mode, where you call the plays!",
	'Nintendo Entertainment System (NES)',
	'2',
	'false',
	'sports',
	'12/01/1991',
	'Tecmo',
	'Tecmo',
	'http://thegamesdb.net/banners/boxart/original/front/1905-1.jpg',
	'http://thegamesdb.net/banners/boxart/original/back/1905-1.jpg',
	'',
	'http://thegamesdb.net/banners/_gameviewcache/publishers/69-folder.png',
	'7.99',
	'2'
), (
	'Pirates: The Legend of Black Kat',
	"More an action-adventure game than a straight naval sim, Pirates: The Legend of Black Kat is designed to offer PS2 and Xbox gamers the chance to live the free but dangerous life of a true pirate. Players will explore five strange new lands that hold unimagined treasures for those brave and skilled enough to claim them. Battle and conquest are also important ingredients in a pirate's lifestyle and combat takes place both on land and on the high seas. The player's character is quick with a sword and can increase her swashbuckling skills with experience. 

	Similarly, wealth gained from adventure and victory allows the pirate to upgrade to larger ships with more deadly weaponry. A dozen unique fighting vessels will become available to skilled captains, along with special accoutrements that afford the ships extra powers. Sea battles involve a realistic combination of positioning and timing, as tall ships align themselves to fire on enemy vessels from port- and starboard-mounted weapons and time must be spent reloading the powerful cannons and guns after each shot. The ability to repair damage on the fly is also an important strategic consideration in ship-to-ship fights.",
	'Sony Playstation 2',
	'2',
	'false',
	'action, adventure',
	'02/19/2002',
	'Westwood Studios, Akella',
	'Electronic Arts',
	'http://thegamesdb.net/banners/boxart/original/front/12932-1.jpg',
	'',
	'',
	'http://thegamesdb.net/banners/_gameviewcache/publishers/0-EA_logo.png',
	'18.99',
	'10'
), (
	'Medal of Honor: Underground',
	"The game is a prequel to Medal of Honor and it is set in the early stages of WWII. You play as Manon Batiste, who briefed the missions for you in the original Medal of Honor. She is a new member of a small band of French rebels who fight against the tyranny of the Germans.

	There are 7 missions in total, featuring 12 different historical weapons. There are NPCs helping you out by cracking safes and driving. Not all enemies are on foot; expect to face tanks and bikes amongst other things. Enemy AI is responsive and sometimes surprising.",
	'Sony Playstation',
	'2',
	'false',
	'shooter',
	'11/25/2000',
	'DreamWorks Interactive',
	'Electronic Arts ',
	'http://thegamesdb.net/banners/boxart/original/front/8288-1.jpg',
	'http://thegamesdb.net/banners/boxart/original/back/8288-1.jpg',
	'http://thegamesdb.net/banners/clearlogo/8288.png',
	'http://thegamesdb.net/banners/_gameviewcache/publishers/0-EA_logo.png',
	'10.99',
	'3'
), (
	"Oddworld: Stranger's Wrath HD",
	"The premise of Oddworld: Stranger's Wrath is that the bounty hunter Stranger must earn moolah (in-game money) by tracking down outlaws with bounties on their heads and apprehending them, bringing them in dead or alive. The game utilizes both third and first-person perspectives. In third person, the player controls Stranger when travelling long distance, platform jumping, rope climbing and melee combat while first person is like that of first person shooter games where ranged weapons are used. Enemies can be approached head on like a straight up action game or stealthily by hiding in long grass out of enemy sight (as indicated via mini map) and luring foes away from or toward the player.[9] Once enemies are encountered, they can be killed or knocked down/stunned temporarily; in this state they can be captured, thus earning more moolah than if they had been captured dead.[10] Upon an attempted capture, Stranger is unable to perform other actions and thus is vulnerable. The player has two status bars, health and stamina. When damage is taken, the health bar drops; if it fully depletes, it will result in the death of Stranger. Stamina drops when the player performs actions like melee attacks or falls from a great height. While it refills itself over time, it can be used to shake off health-bar damage, thus healing the player, but draining the stamina quicker.[9]
	One of the game's main features is Stranger's crossbow that is used in a first person perspective that uses live ammunition in the form of using small fictional versions of real creatures as projectiles for differing effects. Live ammunition can be bought from the game's vendors or found scattered throughout the game world. When acquired, two different kinds of ammo can be assigned to the crossbow at any given time for two kinds of firing attack.[3] There are nine critters in total that can be used as ammo, such as Stunkz for stunning large groups of enemies, Thudslugs that work as cannonballs, Boombats that work as rockets, and Bees that are fired at foes like an automatic rifle.[3]",
	'Sony Playstation 3',
	'1',
	'false',
	'action, adventure',
	'12/27/2011',
	'Oddworld Inhabitants',
	'Oddworld Inhabitants',
	'http://thegamesdb.net/banners/boxart/original/front/15028-1.jpg',
	'',
	'http://thegamesdb.net/banners/clearlogo/15028.png',
	'',
	'12.99',
	'0'
), (
	'GameBoy Wars 2',
	"Game Boy Wars 2, the second of the Game Boy Wars sequels by Hudson Soft, was released on November 20, 1998. It features support for the Super Game Boy and Game Boy Color. The CPU's decision-making algorithm has once again been improved and the game now displays which spaces the player can move into or attack when they're moving a unit, allowing for clearer decision making process for the player. There are 54 new maps in Game Boy Wars 2.",
	'Nintendo Game Boy',
	'2',
	'false',
	'strategy',
	'11/20/1997',
	'Hudson Soft ',
	'Hudson Soft ',
	'http://thegamesdb.net/banners/boxart/original/front/19080-1.jpg',
	'',
	'',
	'http://thegamesdb.net/banners/_gameviewcache/publishers/0-Hudson.png',
	'6.99',
	'1'
), (
	"Disney's Hercules",
	"You are Hercules... the strongest man on Earth. After learning of your true origins, you are informed by the mighty Zeus that no mortal may join the gods unless he has proven himself a hero. So, the adventure begins. Do what you must to pass each of your deadly tests, become a true hero and take your rightful place on Mt. Olympus!",
	'Nintendo Game Boy',
	'1',
	'false',
	'action, platform',
	'07/01/1997',
	'Tiertex Design Studios',
	'THQ',
	'http://thegamesdb.net/banners/boxart/original/front/21652-1.jpg',
	'',
	'',
	'http://thegamesdb.net/banners/_gameviewcache/publishers/0-THQ.png',
	'4.99',
	'3'
), (
	'The Testament of Sherlock Holmes',
	"Scrutinized by Scotland Yard, doubted by his stalwart companion Dr. John Watson, and behaving more erratically than ever, Sherlock Holmes is in what might be his darkest hour yet. His recent triumph in the case of a missing set of priceless jewels has turned to disaster; the necklace's owner accuses Holmes of returning a forgery to him, and there seems to be no evidence at the ready to clear his name. Has Sherlock Holmes become a criminal? If he is indeed a thief, what else is he capable of? As the questions and suspicions mount, will salvation be found or will there be nothing to stop the famous detective's seeming descent into darkness...",
	'Sony Playstation 3',
	'1',
	'false',
	'adventure',
	'09/25/2012',
	'Frogwares',
	'Atlus',
	'http://thegamesdb.net/banners/boxart/original/front/11450-1.jpg',
	'',
	'',
	'http://thegamesdb.net/banners/_gameviewcache/publishers/4-folder.png',
	'24.99',
	'5'
), (
	'Deer Drive',
	"Bring all the ammo you can get your hands on, because open season just arrived - big time! Deer Drive is an arcade-style 3D deer hunting game - take aim from cover, and pick off the best trophies. It's just pure shooting fun, as herds of deer are driven into your sights!",
	'Nintendo Wii',
	'4',
	'true',
	'shooter',
	'12/16/2008',
	'Kouyousha',
	'Mastiff',
	'http://thegamesdb.net/banners/boxart/original/front/14915-1.jpg',
	'',
	'',
	'',
	'7.99',
	'10'
), (
	'Bubsy in: Claws Encounters of the Furred Kind',
	"In this 15-level action game the player is Bubsy the bobcat, who has to defeat the Woolies the aliens, which steal balls of yarn. There are five different locations such as jungle, wild west, etc., where the player has to jump and land on their enemies to kill them. Each time to finish the level the player has to defeat the boss, who sits in an alien ship.",
	'Sega Mega Drive',
	'2',
	'false',
	'platform',
	'01/01/1993',
	'Accolade',
	'Accolade',
	'http://thegamesdb.net/banners/boxart/original/front/23634-1.png',
	'',
	'http://thegamesdb.net/banners/clearlogo/23634.png',
	'http://thegamesdb.net/banners/_gameviewcache/publishers/0-Accolade.png',
	'8.99',
	'10'
), (
	'Kung Fu High Impact',
	"Release your inner Bruce Lee!
	It's YOU in the game!",
	'Microsoft Xbox 360',
	'1',
	'false',
	'fighting',
	'11/21/2011',
	'Virtual Air Guitar Company',
	'UTV True Games',
	'http://thegamesdb.net/banners/boxart/original/front/8873-1.jpg',
	'http://thegamesdb.net/banners/boxart/original/back/8873-1.jpg',
	'',
	'http://thegamesdb.net/banners/_gameviewcache/publishers/0-logo_USGames.jpg',
	'7.99',
	'10'
), (
	'Buzz Lightyear of Star Command',
	"Buzz Lightyear is out to rid the universe of evil. With the aid of his friends at Star Command Mira, Booster, and X-R Buzz will battle Emperor Zurg, Gravatina, Torque, Skreel, and others in 14 levels that span seven different worlds. On each stage, chase the villain causing trouble and try to beat him to the getaway point. Along the way, pick up coins that can be used to purchase new weapons (arc laser, ice gun, proximity grenades, rocket launcher, gatling gun, and others), shields, jetpacks, hover boards, and other items. Cash can also be used to purchase the services of boost pads and teleports that will let Buzz bypass certain portions of the level. Will Buzz be able to put an end to Emperor Zurg's attempts to take over the universe? Only by playing BUZZ LIGHTYEAR OF STAR COMMAND will you be able to find the answers to that question.",
	'Sony Playstation',
	'1',
	'false',
	'action',
	'10/12/2000',
	"Traveller's Tales",
	'Activision',
	'http://thegamesdb.net/banners/boxart/original/front/14078-1.jpg',
	'',
	'',
	'http://thegamesdb.net/banners/_gameviewcache/publishers/0-folder2.png',
	'9.99',
	'9'
), (
	'Super Sprint',
	"Super Sprint is a racing game for one or two players. Gameplay is from an overhead view of the racetrack. The racetracks start simple and gradually get more complicated, and may also feature obstacles ranging from traffic cones to tornadoes. Occasionally wrenches will appear in the roadway, and when collected they can be used after a race to power up your car with better tires, better acceleration or a higher top speed.",
	'Nintendo Entertainment System (NES)',
	'2',
	'false',
	'racing',
	'01/01/1989',
	'Atari',
	'Tengen',
	'http://thegamesdb.net/banners/boxart/original/front/2123-1.jpg',
	'http://thegamesdb.net/banners/boxart/original/back/2123-1.jpg',
	'http://thegamesdb.net/banners/clearlogo/2123.png',
	'',
	'6.99',
	'0'
), (
	'Attack of the Mutant Penguins',
	"In the distant galaxy of Bleurggh, an evil (but reasonably stupid) band of aliens picked up some of Earth's television signals. Unfortunately for them, they could only tune in a wildlife program. They figured the Earth would be a pushover to invade, so they disguised themselves as its inhabitants -- penguins! Word of the invasion has reached those champions of intergalactic do-goodery, Bernard and Rodney. Now, with their help, you must prevent the alien mutant penguins from triggering the Doomscale and destroying the Earth. Are you up to the challenge?",
	'Atari Jaguar',
	'1',
	'false',
	'action, puzzle',
	'03/01/1996',
	'Sunrise Games',
	'Atari',
	'http://thegamesdb.net/banners/boxart/original/front/9849-1.jpg',
	'http://thegamesdb.net/banners/boxart/original/back/9849-1.jpg',
	'http://thegamesdb.net/banners/clearlogo/9849.png',
	'http://thegamesdb.net/banners/_gameviewcache/publishers/3-folder.png',
	'9.99',
	'6'
), (
	'Namco x Capcom',
	"The year is 20XX. Arisu Reiji and Xiaomu work for a special unit called Shinra, and they are tasked with investigating spirit and otherworldly disturbances. They are initially investigating a strange 'sleeping sickness' in the Shibuya area of Japan, when it becomes apparent that something much larger is at stake. Characters, both good and evil, from other times and other worlds begin appearing in Japan.",
	'Sony Playstation 2',
	'1',
	'false',
	'role-playing',
	'05/26/2005',
	'Monolith Soft',
	'Namco',
	'http://thegamesdb.net/banners/boxart/original/front/20020-1.jpg',
	'',
	'',
	'http://thegamesdb.net/banners/_gameviewcache/publishers/0-namco.png',
	'10.99',
	'0'
), (
	'Wipeout: The Game',
	"In Wipeout: The Game, players will prove they have what it takes to make it to the grand finale 'Wipeout Zone' for their chance to be proclaimed champion. Four players can compete at the same time, even allowing players to hurl objects at and taunt their opponents. The video game features everything that people love about the hit ABC show, including commentary from the show's hosts, John Anderson, John Henson and co-host Jill Wagner. Players will have to run, jump and dodge all of Wipeout's various obstacles, including the brutal Sucker Punch, the beloved Big Balls, and the insanely difficult Sweeper.",
	'Nintendo Wii',
	'1',
	'false',
	'',
	'06/22/2010',
	'A.C.R.O.N.Y.M. Games',
	'Activision',
	'http://thegamesdb.net/banners/boxart/original/front/25046-1.jpg',
	'http://thegamesdb.net/banners/boxart/original/back/25046-1.jpg',
	'',
	'http://thegamesdb.net/banners/_gameviewcache/publishers/0-folder2.png',
	'12.99',
	'8'
), (
	'Asuka 120% - Burning Festival Final',
	"As it's prequels, this game was only released in Japan. Much of the features were improved from the Limited version for Sega Saturn. In addition, a Windows port of this game titled 'Asuka 120% BURNING Festival Return' was released as the very last entry of the franchise with very minor tweaks added.",
	'Sony Playstation',
	'2',
	'false',
	'fighting',
	'05/27/1999',
	'Success',
	'Family Soft',
	'http://thegamesdb.net/banners/boxart/original/front/25055-1.jpg',
	'http://thegamesdb.net/banners/boxart/original/back/25055-1.jpg',
	'',
	'',
	'8.99',
	'3'
), (
	'NBA 07',
	"NBA 07 is a basketball video game which was released on September 26, 2006. The product features Los Angeles Lakers guard Kobe Bryant on the cover, with his newly chosen jersey number of 24.

	It is the second installment of the NBA: Featuring the Life series by Sony Computer Entertainment, and is a launch game for the PlayStation 3 format. It is the only game released at launch other than Marvel: Ultimate Alliance and Ridge Racer 7 that supports the 1080p high definition video output, which was a major advertising point for the PS3.

	On all consoles, the game uses graphics from TNT's NBA coverage.",
	'Sony Playstation 3',
	'1',
	'false',
	'sports',
	'11/14/2006',
	'Virtual Air Guitar Company',
	'UTV True Games ',
	'http://thegamesdb.net/banners/boxart/original/front/15955-1.jpg',
	'',
	'',
	'',
	'7.99',
	'7'
), (
	'Chicken Shoot',
	"Chicken Shoot is a gallery shooting game based on free 2003 flash game of the same name. Played from the first-person perspective, the player points the Wii remote and shoots all chickens that fly across the screen. Different kinds of guns can be picked up and every now and then enemies thrown an egg towards the screen that needs to be blown up quickly. Extra points are awarded for shooting certain background items, bombs destroy everything on the screen, food can be picked up to refill energy (Arcade) and clocks add more time (Classic).!",
	'Nintendo Wii',
	'1',
	'false',
	'shooter',
	'07/05/2007',
	'Calaris Studios',
	'Destination Software',
	'http://thegamesdb.net/banners/boxart/original/front/7595-1.jpg',
	'http://thegamesdb.net/banners/boxart/original/back/7595-1.jpg',
	'',
	'http://thegamesdb.net/banners/_gameviewcache/publishers/0-dsi.png',
	'6.99',
	'3'
), (
	'Advanced V.G.',
	"An updated version of the original Variable Geo game for the NEC PC9800 which adds three new playable characters, a storyline which features Yuka as the main character (who has a clone), and includes a pair of 'True' bosses, the genetically engineered 'Hybrid' warriors K-1 and K-2. This game was originally released for the NEC Turbo-CD later updated for Sega Saturn and Sony PlayStation with updated graphics and sound. The only major difference between the Saturn and PlayStation versions is that the Saturn version retains the 'Graphic Mode' setting which allows the viewing of the hentai scenes, not available in the PlayStation version.",
	'Sony Playstation',
	'2',
	'false',
	'fighting',
	'03/19/1996',
	'TGL',
	'TGL',
	'http://thegamesdb.net/banners/boxart/original/front/25048-1.jpg',
	'http://thegamesdb.net/banners/boxart/original/back/25048-1.jpg',
	'',
	'',
	'11.99',
	'0'
), (
	'Spice World',
	"Join the Spice Girls as they enter their own interactive dimension.

Interactive magazine with exclusive interviews and behind-the-scenes footage.
Create your own remixes of five of your favorite Spice Girls songs.
Become your favorite Spice Girl and practice individual dance routines.
Choreograph all the Spice Girls for their special live shows - on your TV!",
	'Sony Playstation',
	'1',
	'false',
	'music',
	'07/31/1998',
	'SCE Studio Soho',
	'Sony',
	'http://thegamesdb.net/banners/boxart/original/front/13585-1.jpg',
	'http://thegamesdb.net/banners/boxart/original/back/13585-1.jpg',
	'',
	'http://thegamesdb.net/banners/_gameviewcache/publishers/0-sony.png',
	'6.99',
	'0'
), (
	'Guilty Gear Isuka',
	"An awesome anime fighting game from Sammy that features 4 player head to head action.",
	'Arcade',
	'4',
	'false',
	'fighting',
	'10/01/2004',
	'Sammy',
	'Sammy',
	'http://thegamesdb.net/banners/boxart/original/front/14957-1.jpg',
	'',
	'http://thegamesdb.net/banners/clearlogo/14957.png',
	'',
	'8.99',
	'3'
), (
	'Classic NES Series: The Legend of Zelda',
	"The Legend of Zelda invented a genre and captivated a gaming generation. Now you can play the timeless NES adventure on your Game Boy Advance! The evil warlock Ganon has imprisoned Princess Zelda and plunged the peaceful land of Hyrule into darkness and despair. Only a young boy named Link has the courage to answer the call for a hero. Will he find the lost Triforce fragments, slay Ganon, and save Princess Zelda? Only you can decide the fate of Hyrule!",
	'Nintendo Game Boy Advance',
	'1',
	'false',
	'action, adventure',
	'06/07/2004',
	'Nintendo',
	'Nintendo',
	'http://thegamesdb.net/banners/boxart/original/front/14617-1.jpg',
	'http://thegamesdb.net/banners/boxart/original/back/14617-1.jpg',
	'http://thegamesdb.net/banners/clearlogo/14617.png',
	'http://thegamesdb.net/banners/_gameviewcache/publishers/0-nintendo.png',
	'17.99',
	'0'
), (
	'Adventure Apes and the Mayan Mystery',
	"The Mayan Mystery is a retro-inspired metroidvania with an emphasis on exploration. You play as Mitch, and with the help of your best friend (Otis) and mentor (Dr.A), must stop Horatio Hawk from escaping the Mayan temple with a magical artifact!

This is the first in a series of games that will take the Adventures Apes from one location to the next, one era to the next, all in an effort to keep the world's most precious treasures out of Horatio's hands!

The full version one the Adventure Apes Webpage has 5 bosses and more than 100 rooms plus an illustrated instruction booklet! :)",
	'PC',
	'1',
	'false',
	'platform',
	'05/05/2012',
	'ScaryPotatos',
	'',
	'http://thegamesdb.net/banners/boxart/original/front/16859-1.jpg',
	'',
	'',
	'',
	'5.99',
	'7'
), (
	'Donkey Kong Country 2',
	"The Donkey Kong Country series returns to the Game Boy Advance in a sequel that features Dixie Kong. She and Diddy Kong must team up to rescue Donkey Kong from the evil Kaptain K. Rool. You'll play as both Diddy and Dixie, and master their different attacks. Test your skills and beat the clock in Diddy's Dash, or race against your friends to see who's the fastest. You can play the game solo or challenge your friends in new bonus games such as Funky's Flights and Bag a Bug.",
	'Nintendo Game Boy Advance',
	'1',
	'false',
	'platform',
	'11/15/2004',
	'Rare',
	'Nintendo',
	'http://thegamesdb.net/banners/boxart/original/front/3392-1.jpg',
	'http://thegamesdb.net/banners/boxart/original/back/3392-1.jpg',
	'',
	'http://thegamesdb.net/banners/_gameviewcache/publishers/0-nintendo.png',
	'10.99',
	'0'
), (
	'102 Dalmatians: Puppies to the Rescue',
	"The game itself follows the films' storyline loosely. The player can choose the role of one of two dalmatians, Oddball or Domino, who are out in the backyard looking for treasure. It is not long before the player realizes that a toy found buried in a park was made at one of Cruella de Vil's toy factories; this alludes to the fact that Cruella's toy sales are down, which ultimately leads to the problem in the storyline. Facing financial ruin from lack of sales, Cruella sets an evil plan in motion - to reprogram her toys to capture any pets in sight. Oddball and Domino are the only puppies in their family who have not been captured when they return from the park. Their parents, Dottie and Dipstick, set out to rescue their puppies, commanding Oddball and Domino to stay home and 'be good.' The puppies do not listen, and are soon out on their biggest adventure yet - to save their brothers and sisters, and their parents who are captured along the way.",
	'Sega Dreamcast',
	'1',
	'false',
	'action, platform',
	'11/15/2000',
	'Crystal Soft',
	'Eidos Interactive',
	'http://thegamesdb.net/banners/boxart/original/front/3524-1.jpg',
	'',
	'http://thegamesdb.net/banners/clearlogo/3524.png',
	'http://thegamesdb.net/banners/_gameviewcache/publishers/15-folder.png',
	'3.99',
	'0'
), (
	 'Marvel Nemesis: Rise of the Imperfects',
	 'When New York City is attacked by aliens, the greatest heroes (and villains) in the Marvel Universe confront them. Marvel Nemesis has two playing modes, a single-player story mode, where players brawl their way through a Mark Millar scripted tale, and a single- or two-player versus mode pitting heroes and villains against each other in a sandbox arena. Famous Marvel characters have been reimagined by artist Jae Lee and new characters have been created for this game series.',
	 'Nintendo GameCube',
	 '2',
	 'false',
	 'Action, Fighting',
	 '09/20/2005',
	 'EA',
	 'EA',
	 'http://thegamesdb.net/banners/boxart/original/front/8723-1.jpg',
	 'http://thegamesdb.net/banners/boxart/original/back/8723-1.jpg',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-EA_logo.png',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-EA_logo.png',
	 '24.99',
	 '5'
 ),	(
	 'Street Fighter X Tekken',
	 'The long awaited clash between the two leaders in the fighting genre can now be played at home… AND on the go! Street Fighter X Tekken on the PlayStation®Vita expands on the action-packed console experience, delivering competitive co-op fun that players of all skill levels can enjoy. With the full roster of 55 playable characters and new exclusive features, Street Fighter X Tekken on the PlayStation®Vita is packed with tons of content and boasts one of the most robust character line-ups in fighting game history.',
	 'Sony Playstation Vita',
	 '4',
	 'true',
	 'Fighting',
	 '10/23/2012',
	 'Capcom, Namco',
	 'Capcom',
	 'http://thegamesdb.net/banners/boxart/original/front/13283-1.jpg',
	 '',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-namco.png',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/8-folder.png',
	 '37.99',
	 '10'
 ),	(
	 'Far Cry 4',
	 'The single-player story follows Ajay Ghale, who initially returns to his home country Kyrat–a wild region of the Himalayas struggling under the regime of despotic self-appointed king Pagan Min (played by Troy Baker)–to scatter his mothers ashes, but becomes caught up in a civil war.',
	 'Sony Playstation 3',
	 '1',
	 'true',
	 'Action, Adventure, Shooter',
	 '11/18/2014',
	 'Ubisoft',
	 'Ubisoft',
	 'http://thegamesdb.net/banners/boxart/original/front/20813-1.jpg',
	 '',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/72-folder.png',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/72-folder.png',
	 '49.99',
	 '15'
 ), (
	 'Tony Hawks Pro Skater 2X',
	 'Tony Hawks Pro Skater 2x was designed to take full advantage of the technical capabilities of Xbox. The game features the franchises signature gameplay, intuitive controls, all of the levels from both Tony Hawks Pro Skater 2 and the original Tony Hawks Pro Skater, in addition to more populated environments, brand new levels, realistic special effects and smoother lifelike animations. The inclusion of system link gameplay brings the skateboarding experience to life.',
	 'Microsoft Xbox',
	 '2',
	 'false',
	 'Action, Sports',
	 '11/14/2001',
	 'Treyarch',
	 'Activision',
	 'http://thegamesdb.net/banners/boxart/original/front/6219-1.jpg',
	 'http://thegamesdb.net/banners/boxart/original/back/6219-1.jpg',
	 '',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-folder2.png',
	 '9.99',
	 '2'
 ),	(
	 'Fight Club',
	 'Fight Club is based on David Finchers film adaption of Chuck Palahniuks novel of the same name. Fed up with consumerist American culture, a fight club is founded as a new type of therapy through bare-knuckle fighting. The game focuses on the fights and uses many characters and environments from the original story. You can create a new fighter or clone one of the generated characters. There are three general fighting styles to choose from: grappling, kung fu or brawling.',
	 'Microsoft Xbox',
	 '2',
	 'false',
	 'fighting',
	 '11/16/2004',
	 'Genuine Games ',
	 'Vivendi',
	 'http://thegamesdb.net/banners/boxart/original/front/6062-1.jpg',
	 'http://thegamesdb.net/banners/boxart/original/back/6062-1.jpg',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-logo_USGames.jpg',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-vivendi.png',
	 '22.99',
	 '5'
 ),	(
	 'Taito Legends',
	 'The complete Taito Legends title list: Space Invaders (1978), Phoenix(1980), Space Invaders Part 2 (1980), Colony 7 (1981), Electric Yoyo (1982), Jungle Hunt (1982), Zoo Keeper (1982), Elevator Action (1983), Great Swordsman (1984), Return of the Invaders (1985), Bubble Bobble (1986), Gladiator (1986), Tokio (1986), Exzisus (1987), Plump Pop (1987), Operation Wolf (1987), Rainbow Islands (1987), Rastan (1987), Super Qix (1987), The New Zealand Story (1988), Operation Thunderbolt (1988), Battle Shark (1989), Continental Circus (1989), Plotting (1989), Volfied (1989), Ninja Kids (1990), Space Gun (1990), Thunderfox (1990) Tube It (1993).',
	 'Sony Playstation 2',
	 '2',
	 'false',
	 'Action, Platform, Puzzle, Racing, Shooter ',
	 '10/25/2005',
	 'Empire Oxford',
	 'Sega',
	 'http://thegamesdb.net/banners/boxart/original/front/12830-1.jpg',
	 'http://thegamesdb.net/banners/boxart/original/back/12830-1.jpg',
	 '',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/57-folder.png',
	 '14.99',
	 '1'
 ), (
	 'Agassi Tennis Generation',
	 'Agassi Tennis Generation brings you up close and personal to the biggest stars in tennis. Play as Andre Agassi, or compete against him, as you smash, volley, lob, and serve on courts from all over the world in 16 tournaments. The game features 32 unique players with realistic movements, various court surfaces, and three challenging game modes including Quick Match, Arcade, and Tournament. Can you win your way to the top ranks of tennis stardom?',
	 'Sony Playstation 2',
	 '4',
	 'false',
	 'Sports',
	 '08/25/2003',
	 'Aqua Pacific',
	 'Dreamcatcher Interactive',
	 'http://thegamesdb.net/banners/boxart/original/front/18838-1.jpg',
	 'http://thegamesdb.net/banners/boxart/original/back/18838-1.jpg',
	 '',
	 '',
	 '15.99',
	 '3'
 ), (
	 'WWE All Stars',
	 'WWE All Stars can be seen as a successor to WWF Wrestlemania: The Arcade Game. Unlike the simulation-based WWE SmackDown vs. Raw games, it offers a more arcade-oriented gameplay, featuring elements of fighting games, with over-the-top moves and unrealistic animation. ',
	 'Sony Playstation 2',
	 '4',
	 'true',
	 'Fighting, Sports ',
	 '03/29/2011',
	 'THQ',
	 'THQ',
	 'http://thegamesdb.net/banners/boxart/original/front/10833-1.jpg',
	 '',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-THQ.png',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-THQ.png',
	 '34.99',
	 '7'
 ), (
	 'Pokémon Moon',
	 'Pokémon Sun and Moon are role-playing video games with adventure elements, based in the fictional Alola region (which itself is loosely based on Hawaiian and Pacific Islander culture), presented in a third-person, overhead perspective. The player controls a young trainer who goes on a quest to catch and train creatures known as Pokémon, and win battles against other trainers. By defeating enemy Pokémon in turn-based battles, the players Pokémon gains experience, allowing them to level up and increase their battle statistics, learn new battle techniques, and in some cases, evolve into more powerful Pokémon.',
	 'Nintendo 3DS',
	 '1',
	 'false',
	 'Adventure, Role-Playing, Strategy ',
	 '11/18/2016',
	 'Game Freak ',
	 'The Pokemon Company',
	 'http://thegamesdb.net/banners/boxart/original/front/41159-1.jpg',
	 '',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/20-folder.png',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-Bethesda.png',
	 '49.99',
	 '20'
 ), (
	 'Pokémon Sun',
	 'Pokémon Sun and Moon are role-playing video games with adventure elements, based in the fictional Alola region (which itself is loosely based on Hawaiian and Pacific Islander culture), presented in a third-person, overhead perspective. The player controls a young trainer who goes on a quest to catch and train creatures known as Pokémon, and win battles against other trainers. By defeating enemy Pokémon in turn-based battles, the players Pokémon gains experience, allowing them to level up and increase their battle statistics, learn new battle techniques, and in some cases, evolve into more powerful Pokémon.',
	 'Nintendo 3DS',
	 '1',
	 'false',
	 'Adventure, Role-Playing, Strategy ',
	 '11/18/2016',
	 'Game Freak ',
	 'The Pokemon Company',
	 'http://thegamesdb.net/banners/boxart/original/front/41158-1.jpg',
	 '',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/20-folder.png',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-Bethesda.png',
	 '49.99',
	 '25'
 ), (
	 'One Piece: Unlimited World Red',
	 'Luffy and his crew go wild in One Piece: Unlimited World Red! Witness the strongest pirate alliance as Straw Hat Luffy and Trafalgar Law, a member of the Royal Seven Warlords of the Sea, team up to challenge the diabolical Donquixote Doflamingo, who will be joining the battle for the first time.',
	 'Sony Playstation 3',
	 '1',
	 'false',
	 'Action',
	 '07/08/2014',
	 'Ganbarion',
	 'Bandai Namco Games',
	 'http://thegamesdb.net/banners/boxart/original/front/29699-1.jpg',
	 '',
	 '',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/5-folder.png',
	 '22.99',
	 '10'
 ), (
	 'Batman: Arkham City',
	 'From Giant Bomb: "Batman: Arkham City is the sequel to Batman: Arkham Asylum, and was released for the Playstation 3 and Xbox 360 on Oct. 18th, 2011. The PC version was released on November 18, 2011, and a version for the Nintendo Wii U is expected some time in 2012. Square-Enix will be publishing all versions of the game in Japan. Taking place a year after Arkham Asylum, the storyline starts with Quincy Sharp, formerly the warden of Arkham Asylum, now the mayor of Gotham City, turning the Gotham slums into a cordoned off prison colony named Arkham City with psychologist Hugo Strange as its warden.',
	 'Sony Playstation 3',
	 '1',
	 'false',
	 'Action, Adventure, Fighting, Stealth',
	 '10/18/2011',
	 'Rocksteady Studios Ltd ',
	 'WB Games ',
	 'http://thegamesdb.net/banners/boxart/original/front/9058-1.png',
	 'http://thegamesdb.net/banners/boxart/original/back/9058-1.png',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-TornBanner.png',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/77-folder.png',
	 '39.99',
	 '30'
 ), (
	 'Castlevania: Lords of Shadow Collection',
	 'Gabriel Belmont learns of a mask with the power to raise the dead and sets out on a mission to obtain it to bring his recently murdered wife back from the dead.',
	 'Sony Playstation 3',
	 '1',
	 'false',
	 'Action',
	 '11/05/2013',
	 'Mercury Steam',
	 'Konami ',
	 'http://thegamesdb.net/banners/boxart/original/front/21422-1.jpg',
	 '',
	 '',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/35-folder.png',
	 '34.99',
	 '15'
 ), (
	 'Saints Row: The Third',
	 'Years after taking Stilwater for their own, the Third Street Saints have evolved from street gang to household brand name, with Saints sneakers, Saints energy drinks and Johnny Gat bobble head dolls all available at a store near you. The Saints are kings of Stilwater, but their celebrity status has not gone unnoticed. The Syndicate, a legendary criminal fraternity with pawns in play all over the globe, has turned its eye on the Saints and demands tribute.',
	 'Sony Playstation 3',
	 '1',
	 'false',
	 'Action',
	 '11/15/2011',
	 'Volition',
	 'THQ',
	 'http://thegamesdb.net/banners/boxart/original/front/8177-1.jpg',
	 '',
	 '',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-THQ.png',
	 '59.99',
	 '12'
 ), (
	 'NBA 2K16',
	 'The NBA 2K franchise is back with the most true-to-life NBA experience to date with NBA 2K16. Guide your MyPLAYER through the complete NBA journey, take control of an entire NBA franchise, or hone your skills online competing against gamers from around the world. With animations that provide smoother movement and more realistic articulation, its certain to be the most authentic NBA gaming experience yet.',
	 'Sony Playstation 3',
	 '4',
	 'true',
	 'Sports',
	 '09/29/2015',
	 '2K',
	 'Visual Concepts',
	 'http://thegamesdb.net/banners/boxart/original/front/29371-1.jpg',
	 '',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-folder.png',
	 '',
	 '19.99',
	 '2'
 ), (
	 'Bloodborne',
	 'Face your fears as you search for answers in the ancient city of Yharnam, now cursed with a strange endemic illness spreading through the streets like wildfire. Danger, death and madness lurk around every corner of this dark and horrific world, and you must discover its darkest secrets in order to survive.',
	 'Sony Playstation 4',
	 '1',
	 'false',
	 'Action, Role-Playing',
	 '03/24/2015',
	 'FromSoftware ',
	 'Sony Computer Entertainment',
	 'http://thegamesdb.net/banners/boxart/original/front/20960-1.jpg',
	 '',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-fromsoftware.png',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-sony.png',
	 '29.99',
	 '4'
 ), (
	 'Destiny 2',
	 'New Legends Will Rise, A new adventure for every player, with new worlds to explore, new stories to tell, new powers to acquire, new loot to earn, and much much more. Note: This edition doesnt contain 3 actual figurines the characters shown in the image on site is simply demonstrating the salute in game character.',
	 'Microsoft Xbox One',
	 '1',
	 'false',
	 'Action, MMO, Role-Playing, Shooter ',
	 '10/24/2017',
	 'Bungie',
	 'Activision ',
	 'http://thegamesdb.net/banners/boxart/original/front/49324-1.jpg',
	 '',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/7-folder.png',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-folder2.png',
	 '69.99',
	 '5'
 ), (
	 'Overwatch',
	 'Overwatch is an upcoming multiplayer first-person shooter in development by Blizzard Entertainment. Unveiled at BlizzCon 2014, the game emphasizes cooperative gameplay using a cast of various heroes, each with their own abilities and roles within a team.',
	 'Microsoft Xbox One',
	 '4',
	 'false',
	 'Role-Playing, Strategy',
	 '05/24/2016',
	 'Blizzard ',
	 'Blizzard ',
	 'http://thegamesdb.net/banners/boxart/original/front/36252-1.jpg',
	 '',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/1-Blizzard_Entertainment_Logo.svg.png',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/1-Blizzard_Entertainment_Logo.svg.png',
	 '64.99',
	 '10'
 ), (
	 'Deus Ex: Mankind Divided',
	 'Deus Ex: Mankind Divided is the next-generation evolution of the futuristic stealth action-RPG series. This is the first game in the Deus Ex: Universe multimedia project, an endeavor to create multiple productions (including games, minigames, books, graphic novels and more) set in this bleak cyberpunk world.',
	 'Microsoft Xbox One',
	 '1',
	 'false',
	 'Action',
	 '08/23/2016',
	 'Eidos Studios - Montreal ',
	 'Square Enix ',
	 'http://thegamesdb.net/banners/boxart/original/front/39774-1.jpg',
	 '',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/15-folder.png',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-square.png',
	 '49.99',
	 '7'
 ), (
	 'Alien: Isolation',
	 'Discover the true meaning of fear in Alien: Isolation, a survival horror set in an atmosphere of constant dread and mortal danger. Fifteen years after the events of Alien, Ellen Ripleys daughter, Amanda enters a desperate battle for survival, on a mission to unravel the truth behind her mothers disappearance. As Amanda, you will navigate through an increasingly volatile world as you find yourself confronted on all sides by a panicked, desperate population and an unpredictable, ruthless Alien. Underpowered and underprepared, you must scavenge resources, improvise solutions and use your wits, not just to succeed in your mission, but to simply stay alive.',
	 'Sony Playstation 4',
	 '1',
	 'false',
	 'Action, Horror ',
	 '10/07/2014',
	 'Creative Assembly ',
	 'Sega',
	 'http://thegamesdb.net/banners/boxart/original/front/21192-1.jpg',
	 '',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/0-Ca_logo.png',
	 'http://thegamesdb.net/banners/_gameviewcache/publishers/57-folder.png',
	 '14.99',
	 '2');